import type { ZodTypeAny } from 'zod';
export declare function getObjectShape(schema: any): Record<string, ZodTypeAny>;
export declare function getArrayElement(schema: any): ZodTypeAny;
export declare function getInnerType(schema: any): ZodTypeAny;
export declare function getDefaultValue(schema: any): unknown;
export declare function isOptionalish(schema: any): boolean;
export declare function unwrapSchema(schema: any): ZodTypeAny;
export declare function getNumberChecks(schema: any): any[];
export declare function getUnionOptions(schema: any): ZodTypeAny[];
export declare function isZodType(schema: any, typeName: string): boolean;
export declare const isZodObject: (schema: any) => boolean;
export declare const isZodArray: (schema: any) => boolean;
export declare const isZodNumber: (schema: any) => boolean;
export declare const isZodString: (schema: any) => boolean;
export declare const isZodBoolean: (schema: any) => boolean;
export declare const isZodDate: (schema: any) => boolean;
export declare const isZodUnion: (schema: any) => boolean;
export declare const isZodOptional: (schema: any) => boolean;
export declare const isZodNullable: (schema: any) => boolean;
export declare const isZodDefault: (schema: any) => boolean;
